In [1]:
from pathlib import Path
import mesa_runner as mr
import pandas as pd
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

In [2]:
mconf = mr.MesaConfig.setup(mesa_dir='/Users/janhenneco/software/mesa/mesa-r24.08.1', version_name='r24.08.1')
def_opts = mr.build_defaults_options_from_config(mconf)

original_workdir_path = '/Users/janhenneco/GitHub/mesa-runner/tests/data_for_tests/r24.08.1/workdirs/high_mass'

og_model = mr.Model.empty(name='original_hm_model')
mr.import_inlists_from_dir(model=og_model, source_dir=original_workdir_path, default_options=def_opts, config=mconf)

Model(name='original_hm_model', model_path=None, mesa_version=MesaVersion(version_name='r24.08.1', scheme='release', revision=None, year=24, month=8, patch=1), model_id='4c014e017c1b4d15b4a236e8766533f7', state=<ModelState.DRAFT: 'draft'>, inlists={'inlist': Inlist(name='inlist', mesa_version=MesaVersion(version_name='r24.08.1', scheme='release', revision=None, year=24, month=8, patch=1), options={'read_extra_star_job_inlist(2)': MesaOption(name='read_extra_star_job_inlist(2)', default_option='.false.', description='You can split your ``star_job`` inlist into pieces using the following controls.\nBTW: it works recursively, so the extras can read extras too.\nif ``read_extra_star_job_inlist(i)`` is true,\nthen read &star_job from this namelist file', namelist='star_job', current_value='.true.'), 'extra_star_job_inlist_name(2)': MesaOption(name='extra_star_job_inlist_name(2)', default_option="'undefined'", description='', namelist='star_job', current_value="'inlist_high_mass'"), 'read_extra_eos_inlist(1)': MesaOption(name='read_extra_eos_inlist(1)', default_option='.false.', description='One can split an eos inlist into pieces using the following parameters.\nIt works recursively, so the extras can read extras too.', namelist='eos', current_value='.true.'), 'extra_eos_inlist_name(1)': MesaOption(name='extra_eos_inlist_name(1)', default_option="'undefined'", description='', namelist='eos', current_value="'inlist_high_mass'"), 'read_extra_kap_inlist(1)': MesaOption(name='read_extra_kap_inlist(1)', default_option='.false.', description='One can split a kap inlist into pieces using the following parameters.\nIt works recursively, so the extras can read extras too.', namelist='kap', current_value='.true.'), 'extra_kap_inlist_name(1)': MesaOption(name='extra_kap_inlist_name(1)', default_option="'undefined'", description='', namelist='kap', current_value="'inlist_high_mass'"), 'read_extra_controls_inlist(1)': MesaOption(name='read_extra_controls_inlist(1)', default_option='.false.', description='One can split controls inlist into pieces using the following parameters.\nBTW: it works recursively, so the extras can read extras too.\nIf ``read_extra_controls_inlist(1)`` is true, then read &controls from this namelist file.', namelist='controls', current_value='.true.'), 'extra_controls_inlist_name(1)': MesaOption(name='extra_controls_inlist_name(1)', default_option="'undefined'", description='', namelist='controls', current_value="'inlist_high_mass'"), 'read_extra_pgstar_inlist(1)': MesaOption(name='read_extra_pgstar_inlist(1)', default_option='.false.', description='the PGSTAR extras work the same as for the star controls', namelist='pgstar', current_value='.true.'), 'extra_pgstar_inlist_name(1)': MesaOption(name='extra_pgstar_inlist_name(1)', default_option="'undefined'", description='', namelist='pgstar', current_value="'inlist_pgstar'")}, additional_options=[], empty_namelists=set(), source_path=PosixPath('/Users/janhenneco/GitHub/mesa-runner/tests/data_for_tests/r24.08.1/workdirs/high_mass/inlist')), 'inlist_high_mass': Inlist(name='inlist_high_mass', mesa_version=MesaVersion(version_name='r24.08.1', scheme='release', revision=None, year=24, month=8, patch=1), options={'show_log_description_at_start': MesaOption(name='show_log_description_at_start', default_option='.true.', description='set this false if you want to skip the initial terminal output', namelist='star_job', current_value='.false.'), 'load_saved_model': MesaOption(name='load_saved_model', default_option='.false.', description='By default at the start of a run a zams starting model is loaded,\nand then the ``initial_mass``, ``initial_z``, and ``initial_y`` are adjusted as necessary.\nHowever, there are alternatives.  you can use a model you saved previously,\nor you can request the system to create a pre-main-sequence model.\nBTW: the system finds the zams file by using the control called ``zams_filename``\nthe default zams file is for Z=0.02 and lives in ``data/star_data/zams_models``.\nYou can create your own zams file and use it instead -- see ``test_suite/create_zams``.\nIf ``load_saved_model`` is true, then use the specified model.\nIf ``load_saved_model_for_RSP`` is true, then load the specified model and run it with RSP.', namelist='star_job', current_value='.true.'), 'load_model_filename': MesaOption(name='load_model_filename', default_option="'undefined'", description='', namelist='star_job', current_value="'zams.mod'"), 'save_model_when_terminate': MesaOption(name='save_model_when_terminate', default_option='.false.', description='save final model when a run terminates\nonly happens if satisfy required termination code\nif string is empty, then this matches all termination codes\nthere can be several different alternative termination codes', namelist='star_job', current_value='.true.'), 'save_model_filename': MesaOption(name='save_model_filename', default_option="'undefined'", description='saved model root filename', namelist='star_job', current_value="'final.mod'"), 'required_termination_code_string': MesaOption(name='required_termination_code_string', default_option="''", description='', namelist='star_job', current_value="'xa_central_lower_limit'"), 'set_initial_cumulative_energy_error': MesaOption(name='set_initial_cumulative_energy_error', default_option='.false.', description='set_initial_cumulative_energy_error is done when execute rn script\nset_cumulative_energy_error is done when execute rn script or re script\nset_cumulative_energy_error_at_step is done before the specified step\nin all cases, the value is set to new_cumulative_energy_error', namelist='star_job', current_value='.true.'), 'new_cumulative_energy_error': MesaOption(name='new_cumulative_energy_error', default_option='0d0', description='', namelist='star_job', current_value='0d0'), 'pgstar_flag': MesaOption(name='pgstar_flag', default_option='.false.', description='if true, activates pgplot output', namelist='star_job', current_value='.true.'), 'save_pgstar_files_when_terminate': MesaOption(name='save_pgstar_files_when_terminate', default_option='.false.', description='if true, then when the run terminates,\npgstar outputs files for plots that have ``file_flag = .true.``\nindependently of the corresponding ``file_interval``.', namelist='star_job', current_value='.true.'), 'Zbase': MesaOption(name='Zbase', default_option='-1', description='The MESA/kap parameters are given default values here.\nThe actual values as modified by your inlist are stored in the Kap_General_Info data structure.\nThey can be accessed by code at runtime using the kap_handle to get a pointer to it.\nThe base metallicity for the opacity tables. This provides the\nreference metallicity necessary to calculate element variations.\nPhysically, this usually corresponds to the initial metallicity\nof the model and remains static during the entirety of a\ncalculation. Variations in metallicity from nuclear burning and\nmixing should not alter Zbase as its purpose is to serve as a\nreference metallicity for C and O enhancement during Helium burning.\nSee ``use_Zbase_for_Type1``. By default, Zbase does not typically affect the\nouter regions of a stellar model when the surface metallicity remains\nbelow the initial metallicity (Z < Zbase). Zbase is typically\nonly used for Type2 opacities which operate deeper in the stellar interior.\nSpecific scenarios such as high Z accretion onto a metal poor model\ncan produce a situation where (Z > Zbase). During this scenario\nthe surface metallicity can be enhanced beyond the initial metallicity.\nUsers can opt to exclusively adopt Type1 opacities in this scenario with\nthe ``use_Zbase_for_Type1`` flag.\nNOTE: For wind schemes that scale with metallicity, we use Zbase rather than Z (as long as Zbase > 0).\nThis is because wind mass loss rate is primarily determined by iron opacity,\nwhich is unlikely to change during the evolution.\nZbase must be set if using kapCN, AESOPUS, or Type2', namelist='kap', current_value='1d-5'), 'energy_eqn_option': MesaOption(name='energy_eqn_option', default_option="'dedt'", description="Available options are ``'dedt'`` or ``'eps_grav'``.", namelist='controls', current_value="'dedt'"), 'num_trace_history_values': MesaOption(name='num_trace_history_values', default_option='0', description="any valid name for a history data column, such as ``surf_v_rot``\nfor example if you have rapid rotation at the surface,\nyou might want to try something like this:\nnum_trace_history_values = 7\ntrace_history_value_name(1) = 'surf_v_rot'\ntrace_history_value_name(2) = 'surf_omega_div_omega_crit'\ntrace_history_value_name(3) = 'log_rotational_mdot_boost'\ntrace_history_value_name(4) = 'log_total_angular_momentum'\ntrace_history_value_name(5) = 'center n14'\ntrace_history_value_name(6) = 'surface n14'\ntrace_history_value_name(7) = 'average n14'\nvalue must be less than or equal to 10", namelist='controls', current_value='2'), 'trace_history_value_name(1)': MesaOption(name='trace_history_value_name(1)', default_option="''", description='write values to terminal', namelist='controls', current_value="'rel_E_err'"), 'trace_history_value_name(2)': MesaOption(name='trace_history_value_name(2)', default_option="''", description='write values to terminal', namelist='controls', current_value="'log_rel_run_E_err'"), 'max_model_number': MesaOption(name='max_model_number', default_option='-1', description='The code will stop when it reaches this model number.\nNegative means no maximum.', namelist='controls', current_value='1550'), 'use_gold2_tolerances': MesaOption(name='use_gold2_tolerances', default_option='.false.', description='level 2 of gold tolerances for solver solver - tighter than level 1', namelist='controls', current_value='.true.'), 'initial_mass': MesaOption(name='initial_mass', default_option='1', description='NOTE: if you are loading a saved model,\nthen the following initial values are NOT USED to modify the model.\nin particular, you cannot use these to change Y or Z of an existing model.\nif you want to do that, see ``star_job.defaults`` controls such as ``change_Y``.\nhowever, these are reported in output as the initial values for the star.\ninitial mass in Msun units.\ncan be any value you\'d like when  you are creating a pre-main sequence model.\nNOTE: this is not used when loading a saved model.\nhowever is reported in output as the initial mass of the star.\ndon\'t let that confuse you.\nif you are loading a ZAMS model and the requested mass is in the range of\nprebuilt models, the code will interpolate in mass using the closest prebuilt models.\nif the requested mass is beyond the range of the prebuilt models, the code will\nload the closest one and then call "relax mass" to create a model to match the request.\nthe prebuilt range is 0.08 Msun to 100 Msun, so the ``relax_mass``\nmethod is only used for extreme cases.  there are enough prebuilt models that the\ninterpolation in mass seems to work fine for many applications.', namelist='controls', current_value='300'), 'initial_z': MesaOption(name='initial_z', default_option='0.02d0', description="initial metallicity for create pre-ms and create initial model\n``initial_z`` can be any value from 0 to 0.04\nnot used when loading a saved model.\nhowever is reported in output as the initial Z of the star.\nhowever, if you are loading a zams model,\nthen ``initial_z`` must match one of the prebuilt values.\nlook in the ``'data/star_data/zams_models'`` directory\nto see what prebuilt zams Z's are available.\nat time of writing, only 0.02 was included in the standard version of star.", namelist='controls', current_value='1d-5'), 'mixing_length_alpha': MesaOption(name='mixing_length_alpha', default_option='2', description='The mixing length is this parameter times a local pressure scale height.\nTo increase R vs. L, decrease ``mixing_length_alpha``.', namelist='controls', current_value='2'), 'conv_core_gap_dq_limit': MesaOption(name='conv_core_gap_dq_limit', default_option='0d0', description='skip non-convective gaps of less than this limit when reporting convective core size', namelist='controls', current_value='0.1'), 'xa_central_lower_limit_species(1)': MesaOption(name='xa_central_lower_limit_species(1)', default_option="''", description='Lower limits on central mass fractions.\nStop when central abundance drops below this limit.\nCan have up to ``num_xa_central_limits`` of these (see ``star_def.inc`` for value).\n``xa_central_lower_limit_species`` contains an isotope name as defined in ``chem_def.f90``.\n``xa_central_lower_limit`` contains the lower limit value.', namelist='controls', current_value="'h1'"), 'xa_central_lower_limit(1)': MesaOption(name='xa_central_lower_limit(1)', default_option='0', description='', namelist='controls', current_value='0.05'), 'overshoot_scheme(1)': MesaOption(name='overshoot_scheme(1)', default_option="''", description='overshooting\n____________\nThere are two schemes implemented in MESA to treat overshooting:\na step overshoot scheme and an exponential scheme.\nParameters for exponential diffusive overshoot are described in the paper by Falk Herwig,\n"The evolution of AGB stars with convective overshoot", A&A, 360, 952-968 (2000).\nOvershooting depends on the classification of the convective zone and can be different at the top and the bottom of the zone.\nThe overshooting controls are based on convection-zone and convection-boundary matching criteria.\nThese criteria are ``overshoot_zone_type``, ``overshoot_zone_loc`` and ``overshoot_bdy_loc``.\nThe overshooting parameter values corresponding to the first set of matching criteria will be used.\nTherefore, narrower criteria should precede more general ones (i.e have lower array indices).\nThese are arrays of size ``NUM_OVERSHOOT_PARAM_SETS`` which is defined in\n``star_data/public/star_data_def.inc`` (currently 16)', namelist='controls', current_value="'exponential'"), 'overshoot_zone_type(1)': MesaOption(name='overshoot_zone_type(1)', default_option="''", description='', namelist='controls', current_value="'nonburn'"), 'overshoot_zone_loc(1)': MesaOption(name='overshoot_zone_loc(1)', default_option="''", description='', namelist='controls', current_value="'shell'"), 'overshoot_bdy_loc(1)': MesaOption(name='overshoot_bdy_loc(1)', default_option="''", description='', namelist='controls', current_value="'bottom'"), 'overshoot_f(1)': MesaOption(name='overshoot_f(1)', default_option='0d0', description='Amount of overshooting from edge of convective zone\nThese are arrays of size ``NUM_OVERSHOOT_PARAM_SETS`` which is defined in\n``star_data/public/star_data_def.inc`` (currently 16)', namelist='controls', current_value='0.128'), 'overshoot_f0(1)': MesaOption(name='overshoot_f0(1)', default_option='0d0', description='', namelist='controls', current_value='0.100'), 'overshoot_scheme(2)': MesaOption(name='overshoot_scheme(2)', default_option="''", description='overshooting\n____________\nThere are two schemes implemented in MESA to treat overshooting:\na step overshoot scheme and an exponential scheme.\nParameters for exponential diffusive overshoot are described in the paper by Falk Herwig,\n"The evolution of AGB stars with convective overshoot", A&A, 360, 952-968 (2000).\nOvershooting depends on the classification of the convective zone and can be different at the top and the bottom of the zone.\nThe overshooting controls are based on convection-zone and convection-boundary matching criteria.\nThese criteria are ``overshoot_zone_type``, ``overshoot_zone_loc`` and ``overshoot_bdy_loc``.\nThe overshooting parameter values corresponding to the first set of matching criteria will be used.\nTherefore, narrower criteria should precede more general ones (i.e have lower array indices).\nThese are arrays of size ``NUM_OVERSHOOT_PARAM_SETS`` which is defined in\n``star_data/public/star_data_def.inc`` (currently 16)', namelist='controls', current_value="'exponential'"), 'overshoot_zone_type(2)': MesaOption(name='overshoot_zone_type(2)', default_option="''", description='', namelist='controls', current_value="'any'"), 'overshoot_zone_loc(2)': MesaOption(name='overshoot_zone_loc(2)', default_option="''", description='', namelist='controls', current_value="'any'"), 'overshoot_bdy_loc(2)': MesaOption(name='overshoot_bdy_loc(2)', default_option="''", description='', namelist='controls', current_value="'any'"), 'overshoot_f(2)': MesaOption(name='overshoot_f(2)', default_option='0d0', description='Amount of overshooting from edge of convective zone\nThese are arrays of size ``NUM_OVERSHOOT_PARAM_SETS`` which is defined in\n``star_data/public/star_data_def.inc`` (currently 16)', namelist='controls', current_value='0.014'), 'overshoot_f0(2)': MesaOption(name='overshoot_f0(2)', default_option='0d0', description='', namelist='controls', current_value='0.004'), 'photo_interval': MesaOption(name='photo_interval', default_option='50', description='save a photo file for possible restarting when ``mod(model_number, photo_interval) = 0``.\nnote: this replaces the obsolete control ``photostep``.', namelist='controls', current_value='50'), 'profile_interval': MesaOption(name='profile_interval', default_option='50', description='save a model profile info when ``mod(model_number, profile_interval) = 0``.', namelist='controls', current_value='100'), 'history_interval': MesaOption(name='history_interval', default_option='5', description='append an entry to the history.data file when ``mod(model_number, history_interval) = 0``.', namelist='controls', current_value='10'), 'terminal_interval': MesaOption(name='terminal_interval', default_option='1', description='write info to terminal when ``mod(model_number, terminal_interval) = 0``.\nnote: this replaces the obsolete control ``terminal_cnt``.', namelist='controls', current_value='10'), 'write_header_frequency': MesaOption(name='write_header_frequency', default_option='10', description='output the log header info to the terminal\nwhen ``mod(model_number, write_header_frequency*terminal_interval) = 0``.', namelist='controls', current_value='100')}, additional_options=[], empty_namelists={'eos'}, source_path=PosixPath('/Users/janhenneco/GitHub/mesa-runner/tests/data_for_tests/r24.08.1/workdirs/high_mass/inlist_high_mass')), 'inlist_high_mass_header': Inlist(name='inlist_high_mass_header', mesa_version=MesaVersion(version_name='r24.08.1', scheme='release', revision=None, year=24, month=8, patch=1), options={'read_extra_star_job_inlist(2)': MesaOption(name='read_extra_star_job_inlist(2)', default_option='.false.', description='You can split your ``star_job`` inlist into pieces using the following controls.\nBTW: it works recursively, so the extras can read extras too.\nif ``read_extra_star_job_inlist(i)`` is true,\nthen read &star_job from this namelist file', namelist='star_job', current_value='.true.'), 'extra_star_job_inlist_name(2)': MesaOption(name='extra_star_job_inlist_name(2)', default_option="'undefined'", description='', namelist='star_job', current_value="'inlist_high_mass'"), 'read_extra_eos_inlist(1)': MesaOption(name='read_extra_eos_inlist(1)', default_option='.false.', description='One can split an eos inlist into pieces using the following parameters.\nIt works recursively, so the extras can read extras too.', namelist='eos', current_value='.true.'), 'extra_eos_inlist_name(1)': MesaOption(name='extra_eos_inlist_name(1)', default_option="'undefined'", description='', namelist='eos', current_value="'inlist_high_mass'"), 'read_extra_kap_inlist(1)': MesaOption(name='read_extra_kap_inlist(1)', default_option='.false.', description='One can split a kap inlist into pieces using the following parameters.\nIt works recursively, so the extras can read extras too.', namelist='kap', current_value='.true.'), 'extra_kap_inlist_name(1)': MesaOption(name='extra_kap_inlist_name(1)', default_option="'undefined'", description='', namelist='kap', current_value="'inlist_high_mass'"), 'read_extra_controls_inlist(1)':

In [3]:
og_model.inlists['inlist_high_mass'].remove_option('history_interval')
og_model.inlists['inlist_high_mass'].set_option(name='initial_mass',value='299.0',defaults=def_opts)
og_model.inlists['inlist_high_mass'].set_option(name='history_interval',value=1,namelist='controls',defaults=def_opts)
og_model.inlists['inlist_high_mass'].remove_option('overshoot_f(1)')

True

In [4]:
mr.preview(og_model.inlists['inlist_high_mass'].options)

,namelist,name,default,current,description
0,star_job,show_log_description_at_start,.true.,.false.,set this false if you want to skip the initial terminal output
1,star_job,load_saved_model,.false.,.true.,"By default at the start of a run a zams starting model is loaded, and then the ``initial_mass``, ..."
2,star_job,load_model_filename,'undefined','zams.mod',
3,star_job,save_model_when_terminate,.false.,.true.,save final model when a run terminates only happens if satisfy required termination code if strin...
4,star_job,save_model_filename,'undefined','final.mod',saved model root filename
5,star_job,required_termination_code_string,'','xa_central_lower_limit',
6,star_job,set_initial_cumulative_energy_error,.false.,.true.,set_initial_cumulative_energy_error is done when execute rn script set_cumulative_energy_error is...
7,star_job,new_cumulative_energy_error,0d0,0d0,
8,star_job,pgstar_flag,.false.,.true.,"if true, activates pgplot output"
9,star_job,save_pgstar_files_when_terminate,.false.,.true.,"if true, then when the run terminates, pgstar outputs files for plots that have ``file_flag = .tr..."
10,kap,Zbase,-1,1d-5,The MESA/kap parameters are given default values here. The actual values as modified by your inli...
11,controls,energy_eqn_option,'dedt','dedt',Available options are ``'dedt'`` or ``'eps_grav'``.
12,controls,num_trace_history_values,0,2,"any valid name for a history data column, such as ``surf_v_rot`` for example if you have rapid ro..."
13,controls,trace_history_value_name(1),'','rel_E_err',write values to terminal
14,controls,trace_history_value_name(2),'','log_rel_run_E_err',write values to terminal
15,controls,max_model_number,-1,1550,The code will stop when it reaches this model number. Negative means no maximum.
16,controls,use_gold2_tolerances,.false.,.true.,level 2 of gold tolerances for solver solver - tighter than level 1
17,controls,initial_mass,1,299d0,"NOTE: if you are loading a saved model, then the following initial values are NOT USED to modify ..."
18,controls,initial_z,0.02d0,1d-5,initial metallicity for create pre-ms and create initial model ``initial_z`` can be any value fro...
19,controls,mixing_length_alpha,2,2,"The mixing length is this parameter times a local pressure scale height. To increase R vs. L, dec..."
20,controls,conv_core_gap_dq_limit,0d0,0.1,skip non-convective gaps of less than this limit when reporting convective core size
21,controls,xa_central_lower_limit_species(1),'','h1',Lower limits on central mass fractions. Stop when central abundance drops below this limit. Can h...
22,controls,xa_central_lower_limit(1),0,0.05,
23,controls,overshoot_scheme(1),'','exponential',overshooting ____________ There are two schemes implemented in MESA to treat overshooting: a step...
24,controls,overshoot_zone_type(1),'','nonburn',
25,controls,overshoot_zone_loc(1),'','shell',
26,controls,overshoot_bdy_loc(1),'','bottom',
27,controls,overshoot_f0(1),0d0,0.100,
28,controls,overshoot_scheme(2),'','exponential',overshooting ____________ There are two schemes implemented in MESA to treat overshooting: a step...
29,controls,overshoot_zone_type(2),'','any',
30,controls,overshoot_zone_loc(2),'','any',
31,controls,overshoot_bdy_loc(2),'','any',
32,controls,overshoot_f(2),0d0,0.014,Amount of overshooting from edge of convective zone These are arrays of size ``NUM_OVERSHOOT_PARA...
33,controls,overshoot_f0(2),0d0,0.004,
34,controls,photo_interval,50,50,"save a photo file for possible restarting when ``mod(model_number, photo_interval) = 0``. note: t..."
35,controls,profile_interval,50,100,"save a model profile info when ``mod(model_number, profile_interval) = 0``."
36,controls,terminal_interval,1,10,"write info to terminal when ``mod(model_number, terminal_interval) = 0``. note: this replaces the..."
37,controls,write_header_frequency,10,100,"output the log header info to the terminal when ``mod(model_number, write_header_frequency*termin..."
38,controls,history_interval,5,1,"append an entry to the history.data file when ``mod(model_number, history_interval) = 0``."

In [5]:
new_inlist = mr.Inlist.empty(name='inlist_new',mesa_version=mconf.mesa_version)

controls = {'initial_mass': 15.4,
            'overshoot_f(1)': 0.05,
            'overshoot_f0(1)': 0.005
}

star_job = {'use_suzuki_weak_rates': True,
            'show_net_species_info': '.true.'

}

new_inlist.set_options(defaults=def_opts, controls=controls, star_job=star_job)

new_model = og_model.copy(model_copy_name='new_model')
new_model.add_inlist(new_inlist)

In [6]:
print(og_model.created_at)
print(new_model.created_at)

project_dir = mr.create_projectdir(projectdir_path='/Users/janhenneco/GitHub/mesa-runner/tests/data_for_tests/r24.08.1/workdirs/new_proj_dir', mode='star')
new_model_dir = mr.create_modeldir(model=new_model, projectdir_path=project_dir)

2026-05-22 14:28:53.619805+00:00
2026-05-22 14:29:03.263107+00:00

In [18]:
hcl = Path(mconf.mesa_dir) / "star" / "work" / "history_columns.list"
print(hcl.is_file)

<bound method Path.is_file of PosixPath('/Users/janhenneco/software/mesa/mesa-r24.08.1/star/work/history_columns.list')>

In [8]:
mr.preview(new_model.inlists['inlist_high_mass'].options)
# mr.preview(og_model.inlists['inlist_high_mass'].options)

,namelist,name,default,current,description
0,star_job,show_log_description_at_start,.true.,.false.,set this false if you want to skip the initial terminal output
1,star_job,load_saved_model,.false.,.true.,"By default at the start of a run a zams starting model is loaded, and then the ``initial_mass``, ..."
2,star_job,load_model_filename,'undefined','zams.mod',
3,star_job,save_model_when_terminate,.false.,.true.,save final model when a run terminates only happens if satisfy required termination code if strin...
4,star_job,save_model_filename,'undefined','final.mod',saved model root filename
5,star_job,required_termination_code_string,'','xa_central_lower_limit',
6,star_job,set_initial_cumulative_energy_error,.false.,.true.,set_initial_cumulative_energy_error is done when execute rn script set_cumulative_energy_error is...
7,star_job,new_cumulative_energy_error,0d0,0d0,
8,star_job,pgstar_flag,.false.,.true.,"if true, activates pgplot output"
9,star_job,save_pgstar_files_when_terminate,.false.,.true.,"if true, then when the run terminates, pgstar outputs files for plots that have ``file_flag = .tr..."
10,kap,Zbase,-1,1d-5,The MESA/kap parameters are given default values here. The actual values as modified by your inli...
11,controls,energy_eqn_option,'dedt','dedt',Available options are ``'dedt'`` or ``'eps_grav'``.
12,controls,num_trace_history_values,0,2,"any valid name for a history data column, such as ``surf_v_rot`` for example if you have rapid ro..."
13,controls,trace_history_value_name(1),'','rel_E_err',write values to terminal
14,controls,trace_history_value_name(2),'','log_rel_run_E_err',write values to terminal
15,controls,max_model_number,-1,1550,The code will stop when it reaches this model number. Negative means no maximum.
16,controls,use_gold2_tolerances,.false.,.true.,level 2 of gold tolerances for solver solver - tighter than level 1
17,controls,initial_z,0.02d0,1d-5,initial metallicity for create pre-ms and create initial model ``initial_z`` can be any value fro...
18,controls,mixing_length_alpha,2,2,"The mixing length is this parameter times a local pressure scale height. To increase R vs. L, dec..."
19,controls,conv_core_gap_dq_limit,0d0,0.1,skip non-convective gaps of less than this limit when reporting convective core size
20,controls,xa_central_lower_limit_species(1),'','h1',Lower limits on central mass fractions. Stop when central abundance drops below this limit. Can h...
21,controls,xa_central_lower_limit(1),0,0.05,
22,controls,overshoot_scheme(1),'','exponential',overshooting ____________ There are two schemes implemented in MESA to treat overshooting: a step...
23,controls,overshoot_zone_type(1),'','nonburn',
24,controls,overshoot_zone_loc(1),'','shell',
25,controls,overshoot_bdy_loc(1),'','bottom',
26,controls,overshoot_f0(1),0d0,0.100,
27,controls,overshoot_scheme(2),'','exponential',overshooting ____________ There are two schemes implemented in MESA to treat overshooting: a step...
28,controls,overshoot_zone_type(2),'','any',
29,controls,overshoot_zone_loc(2),'','any',
30,controls,overshoot_bdy_loc(2),'','any',
31,controls,overshoot_f(2),0d0,0.014,Amount of overshooting from edge of convective zone These are arrays of size ``NUM_OVERSHOOT_PARA...
32,controls,overshoot_f0(2),0d0,0.004,
33,controls,photo_interval,50,50,"save a photo file for possible restarting when ``mod(model_number, photo_interval) = 0``. note: t..."
34,controls,profile_interval,50,100,"save a model profile info when ``mod(model_number, profile_interval) = 0``."
35,controls,terminal_interval,1,10,"write info to terminal when ``mod(model_number, terminal_interval) = 0``. note: this replaces the..."
36,controls,write_header_frequency,10,100,"output the log header info to the terminal when ``mod(model_number, write_header_frequency*termin..."
37,controls,history_interval,5,1,"append an entry to the history.data file when ``mod(model_number, history_interval) = 0``."

In [ ]:
project_dir = mr.create_projectdir

In [13]:
mr.preview(def_opts.star_job.options)

,namelist,name,default,current,description
0,star_job,mesa_dir,'',,"if set to the empty string, '', then it defaults to using environment variable ``$(MESA_DIR)``"
1,star_job,chem_isotopes_filename,'isotopes.data ',,this file is in ``chem_data`` in ``mesa_data_dir``
2,star_job,pause_before_terminate,.false.,,"if true, then will pause before terminate run. this can be useful if you'd like a chance to look ..."
3,star_job,eosDT_cache_dir,'',,cache directories _________________ mesa uses caches to improve performance. the default location...
4,star_job,ionization_cache_dir,'',,
5,star_job,kap_cache_dir,'',,
6,star_job,rates_cache_dir,'',,
7,star_job,echo_at_start,'',,
8,star_job,echo_at_end,'',,
9,star_job,show_log_description_at_start,.true.,,set this false if you want to skip the initial terminal output
10,star_job,show_net_species_info,.false.,,"if true, then output a list of the species in the current net"
11,star_job,show_net_reactions_info,.false.,,"if true, then output information about the reactions in the current net"
12,star_job,list_net_reactions,.false.,,"if true, then output a simple list of the reactions in the current net"
13,star_job,show_eqns_and_vars_names,.false.,,"if true, then output a list of the names of the equations and variables"
14,star_job,pgstar_flag,.false.,,"if true, activates pgplot output"
15,star_job,disable_pgstar_during_relax_flag,.true.,,"if true, disables pgplot output during relaxation operations"
16,star_job,clear_initial_pgstar_history,.true.,,
17,star_job,clear_pgstar_history,.false.,,
18,star_job,save_pgstar_files_when_terminate,.false.,,"if true, then when the run terminates, pgstar outputs files for plots that have ``file_flag = .tr..."
19,star_job,history_columns_file,'',,"if null string, use default."
20,star_job,profile_columns_file,'',,"if null string, use default."
21,star_job,save_model_number,-111,,"at any point during the run, you can save a model for later use"
22,star_job,save_model_when_terminate,.false.,,save final model when a run terminates only happens if satisfy required termination code if strin...
23,star_job,required_termination_code_string(:),'',,
24,star_job,save_model_filename,'undefined',,saved model root filename
25,star_job,save_photo_when_terminate,.true.,,"if true, then save photo for last model before terminate the run"
26,star_job,profile_starting_model,.false.,,write profile for a specific model number
27,star_job,profile_model_number,-1111,,
28,star_job,show_retry_counts_when_terminate,.true.,,
29,star_job,show_timestep_limit_counts_when_terminate,.true.,,
30,star_job,write_profile_when_terminate,.false.,,write profile to a given name upon termination
31,star_job,filename_for_profile_when_terminate,'',,
32,star_job,save_pulse_data_for_model_number,-111,,write pulsation data for the model (format given by ``s% pulse_data_format``)
33,star_job,save_pulse_data_when_terminate,.false.,,
34,star_job,save_pulse_data_filename,'undefined',,
35,star_job,report_retries,.false.,,in case you want some extra info about retries
36,star_job,load_saved_model,.false.,,"By default at the start of a run a zams starting model is loaded, and then the ``initial_mass``, ..."
37,star_job,load_model_filename,'undefined',,
38,star_job,create_pre_main_sequence_model,.false.,,"If true, the code will create a starting model with uniform composition, a core temperature below..."
39,star_job,pre_ms_T_c,3d5,,Initial center temperature (must be below 1d6). If you have initial convergence problems creating...
40,star_job,pre_ms_guess_rho_c,0,,Guess for initial center density; set to 0 to let the code pick.
41,star_job,pre_ms_d_log10_P,0,,Suggested spacing in pressure between points; set to 0 to let the code pick.
42,star_job,pre_ms_logT_surf_limit,3.7d0,,Model construction is from inside out and stops when reaches either of the following limits.
43,star_job,pre_ms_logP_surf_limit,3.5d0,,
44,star_job,pre_ms_relax_num_steps,300,,Let pre-ms model settle in for this many steps before changing anything else. Make this large eno...
45,star_job,pre_ms_relax_to_start_radiative_core,.true.,,"Let pre-ms model contract until just begins to have a tiny radiative core. i.e., keep going until..."
46,star_job,pre_ms_min_steps_before_check_radiative_core,50,,pre_ms_relax_to_start_radiative_core. wait this many steps before start checking for radiative co...
47,star_job,pre_ms_check_radiative_core_start,1d-6,,
48,star_job,pre_ms_check_radiative_core_stop,1d-3,,
49,star_job,pre_ms_check_radiative_core_Lnuc_div_L_limit,0.1d0,,
50,star_job,pre_ms_check_radiative_core_min_mass,0.3d0,,
51,star_job,create_initial_model,.false.,,"This is an alternative to ``create_pre_main_sequence_model``. If true, creates an adiabatic, cont..."
52,star_job,create_RSP_model,.false.,,
53,star_job,radius_in_cm_for_create_initial_model,0,,Radius in cm and mass in grams.
54,star_job,mass_in_gm_for_create_initial_model,0,,
55,star_job,center_logP_1st_try_for_create_initial_model,10.9d0,,
56,star_job,entropy_1st_try_for_create_initial_model,11.5d0,,
57,star_job,max_tries_for_create_initial_model,100,,
58,star_job,abs_e01_tolerance_for_create_initial_model,1d-4,,
59,star_job,abs_e02_tolerance_for_create_initial_model,1d-4,,
60,star_job,initial_model_relax_num_steps,10,,Let initial model settle in for this many steps before changing anything else.
61,star_job,initial_model_eps,0.05d0,,Integration accuracy.
62,star_job,steps_to_take_before_terminate,-1,,"If >= 0, stop after taking this many steps. Sets ``max_model_number`` = ``model_number`` + ``step..."
63,star_job,stop_if_this_file_exists,'stop_if_this_file_exists',,"Every 100 steps, the code will try to open this file. If the file exists, it will terminate the r..."
64,star_job,set_initial_age,.false.,,These controls enable one to alter the MESA model at the start of a run (``./rn``) or after a res...
65,star_job,initial_age,0,,
66,star_job,set_initial_model_number,.false.,,"if true, set initial model number"
67,star_job,initial_model_number,0,,
68,star_job,set_initial_number_retries,.true.,,"if true, set initial number of retries if false, number of retries set from initial model info"
69,star_job,initial_number_retries,0,,
70,star_job,set_initial_dt,.false.,,"if true, set initial timestep, dt, in years"
71,star_job,years_for_initial_dt,-1,,
72,star_job,seconds_for_initial_dt,-1,,
73,star_job,limit_initial_dt,.false.,,"Like ``set_initial_dt``, but does not increase current value for ``dt_next``. Used in conjunction..."
74,star_job,set_uniform_initial_composition,.false.,,Set uniform composition. This is useful with ``create_pre_main_sequence_model``.
75,star_job,initial_h1,-1,,"if ``set_uniform_initial_composition`` is true, then set hydrogen and helium mass fractions accor..."
76,star_job,initial_h2,-1,,
77,star_job,initial_he3,-1,,
78,star_job,initial_he4,-1,,
79,star_job,initial_zfracs,3,,"if ``set_uniform_initial_composition`` is true, then set metal fractions z fractions -- select on..."
80,star_job,dump_missing_metals_into_heaviest,.true.,,this controls the treatment metals that are not included in the current net. if this flag is true...
81,star_job,file_for_uniform_xa,'',,an alternative to the above ``set_uniform_initial_composition`` method. if ``set_uniform_initial_...
82,star_job,set_uniform_initial_xa_from_file,.false.,,
83,star_job,set_uniform_xa_from_file,.false.,,
84,star_job,mix_section,.false.,,fully mix section of model
85,star_job,mix_initial_section,.false.,,
86,star_job,mix_section_nzlo,-1,,
87,star_job,mix_section_nzhi,-1,,
88,star_job,mix_envelope_down_to_T,0,,fully mix envelope from surface down to given temperature
89,star_job,mix_initial_envelope_down_to_T,0,,
90,star_job,set_abundance,.false.,,"given a ``chem_name`` from ``chem_def``, set its abundance to be ``new_frac`` in a given range of..."
91,star_job,set_initial_abundance,.false.,,
92,star_job,chem_name,'he3',,
93,star_job,new_frac,0,,
94,star_job,set_abundance_nzlo,-1,,
95,star_job,set_abundance_nzhi,-1,,
96,star_job,replace_element,.false.,,replace one iso by another in a given range of cells ``chem_name1`` and ``chem_name2`` from ``che...
97,star_job,replace_initial_element,.false.,,
98,star_job,chem_name1,'he3',,
99,star_job,chem_name2,'he4',,
100,star_job,replace_element_nzlo,-1,,
101,star_job,replace_element_nzhi,-1,,
102,star_job,relax_initial_composition,.false.,,relax composition from current to specified over number of steps. ``relax_composition_filename`` ...
103,star_job,num_steps_to_relax_composition,100,,
104,star_job,relax_composition_filename,'',,
105,star_job,timescale_for_relax_composition,-1d0,,
106,star_job,relax_initial_to_xaccrete,.false.,,"Like ``relax_initial_composition`` (and uses ``num_steps_to_relax_composition``), but new composi..."
107,star_job,relax_Y,.false.,,"some modifications must be done gradually over several steps in ""pseudo"" evolution these operatio..."
108,star_job,change_Y,.false.,,
109,star_job,relax_initial_Y,.false.,,
110,star_job,change_initial_Y,.false.,,
111,star_job,relax_Y_minq,0d0,,
112,star_job,relax_Y_maxq,1d0,,
113,star_job,new_Y,-1,,
114,star_job,relax_Z,.false.,,"``relax_Z = .true.`` gradually changes average Z, reconverging at each step. ``change_Z = .true.`..."
115,star_job,change_Z,.false.,,
116,star_job,relax_initial_Z,.false.,,
117,star_job,change_initial_Z,.false.,,
118,star_job,relax_Z_minq,0d0,,
119,star_job,relax_Z_maxq,1d0,,
120,star_job,new_Z,-1,,
121,star_job,relax_mass,.false.,,Gradually change total mass by a wind to ``new_mass``. ``lg_max_abs_mdot = -4`` means max abs mdo...
122,star_job,relax_initial_mass,.false.,,
123,star_job,new_mass,-1,,
124,star_job,lg_max_abs_mdot,-100,,
125,star_job,relax_mass_to_remove_H_env,.false.,,Gradually reduce total mass by a wind to remove the H envelope. Equivalent to relax_mass with new...
126,star_job,relax_initial_mass_to_remove_H_env,.false.,,
127,star_job,extra_mass_retained_by_remove_H_env,5d-3,,
128,star_job,relax_mass_scale,.false.,,Gradually rescale mass of star to ``new_mass``. Rescales star mass without changing composition a...
129,star_job,relax_initial_mass_scale,.false.,,
130,star_job,dlgm_per_step,1d-3,,
131,star_job,change_mass_years_for_dt,1,,
132,star_job,relax_initial_angular_momentum,.false.,,relax angular momentum from current to specified over a certain amount of relaxation timescales. ...
133,star_job,max_steps_to_relax_angular_momentum,1000,,
134,star_job,timescale_for_relax_angular_momentum,1d-10,,
135,star_job,max_dt_for_relax_angular_momentum,1d-9,,
136,star_job,num_timescales_for_relax_angular_momentum,1000,,
137,star_job,relax_angular_momentum_filename,'',,
138,star_job,relax_angular_momentum_constant_omega_center,.true.,,
139,star_job,relax_initial_entropy,.false.,,relax entropy from current to specified over a certain amount of relaxation timescales. This is d...
140,star_job,max_steps_to_relax_entropy,1000,,
141,star_job,timescale_for_relax_entropy,1d-9,,
142,star_job,max_dt_for_relax_entropy,1d-9,,
143,star_job,num_timescales_for_relax_entropy,100,,
144,star_job,relax_entropy_filename,'',,
145,star_job,get_entropy_for_relax_from_eos,'',,
146,star_job,relax_dxdt_nuc_factor,.false.,,"Gradually rescale ``dxdt_nuc_factor``. At each step, multiply ``dxdt_nuc_factor`` by ``dxdt_nuc_f..."
147,star_job,relax_initial_dxdt_nuc_factor,.false.,,
148,star_job,new_dxdt_nuc_factor,0,,
149,star_job,dxdt_nuc_factor_multiplier,0,,
150,star_job,relax_eps_nuc_factor,.false.,,"Gradually rescale ``eps_nuc_factor``. At each step, multiply ``eps_nuc_factor`` by ``eps_nuc_fact..."
151,star_job,relax_initial_eps_nuc_factor,.false.,,
152,star_job,new_eps_nuc_factor,0,,
153,star_job,eps_nuc_factor_multiplier,0,,
154,star_job,relax_opacity_max,.false.,,"Gradually rescale ``opacity_max``. At each step, multiply ``opacity_max`` by ``opacity_max_multip..."
155,star_job,relax_initial_opacity_max,.false.,,
156,star_job,new_opacity_max,0,,
157,star_job,opacity_max_multiplier,0,,
158,star_job,relax_max_surf_dq,.false.,,"Gradually rescale ``max_surface_cell_dq``. At each step, multiply ``max_surface_cell_dq`` by ``op..."
159,star_job,relax_initial_max_surf_dq,.false.,,
160,star_job,new_max_surf_dq,0,,
161,star_job,max_surf_dq_multiplier,0,,
162,star_job,relax_to_this_tau_factor,-1,,"Must have tau_factor = 1 when atm_option = 'table', as surface of the model must always attach at..."
163,star_job,dlogtau_factor,0.1d0,,
164,star_job,relax_tau_factor,.false.,,
165,star_job,relax_initial_tau_factor,.false.,,
166,star_job,relax_tau_factor_after_core_He_burn,-1,,
167,star_job,relax_tau_factor_after_core_C_burn,-1,,
168,star_job,set_to_this_tau_factor,-1,,"As for ``relax_to_this_tau_factor``, but changes ``tau_factor`` without reconverging."
169,star_job,set_tau_factor,.false.,,
170,star_job,set_initial_tau_factor,.false.,,
171,star_job,set_tau_factor_after_core_He_burn,-1,,
172,star_job,set_tau_factor_after_core_C_burn,-1,,
173,star_job,adjust_tau_factor_to_surf_density,.false.,,"if ``adjust_tau_factor_to_surf_density``, then at start of each step set ``tau_factor`` to curren..."
174,star_job,base_for_adjust_tau_factor_to_surf_density,0d0,,
175,star_job,relax_to_this_opacity_factor,-1,,
176,star_job,d_opacity_factor,0.1d0,,
177,star_job,relax_opacity_factor,.false.,,
178,star_job,relax_initial_opacity_factor,.false.,,
179,star_job,relax_to_this_Tsurf_factor,-1,,
180,star_job,dlogTsurf_factor,0.1d0,,
181,star_job,relax_Tsurf_factor,.false.,,
182,star_job,relax_initial_Tsurf_factor,.false.,,
183,star_job,set_to_this_Tsurf_factor,-1,,"As for ``relax_to_this_Tsurf_factor``, but changes ``Tsurf_factor`` without reconverging."
184,star_job,set_Tsurf_factor,.false.,,
185,star_job,set_initial_Tsurf_factor,.false.,,
186,star_job,relax_mass_change,.false.,,``relax_mass_change_max_yrs_dt`` in years ``relax_mass_change_init_mdot`` in Msun/year
187,star_job,relax_initial_mass_change,.false.,,
188,star_job,relax_mass_change_min_steps,10,,
189,star_job,relax_mass_change_max_yrs_dt,10,,
190,star_job,relax_mass_change_init_mdot,0,,
191,star_job,relax_mass_change_final_mdot,0,,
192,star_job,relax_irradiation,.false.,,extra heat near surface to model irradiation. ``relax_to_this_irrad_flux`` is flux in erg s^-1 cm...
193,star_job,relax_initial_irradiation,.false.,,
194,star_job,relax_to_this_irrad_flux,0,,
195,star_job,relax_irradiation_min_steps,0,,
196,star_job,relax_irradiation_max_yrs_dt,-1,,
197,star_job,irrad_col_depth,-1,,
198,star_job,set_irradiation,.false.,,as for ``relax_irradiation`` but sets values and does not reconverge
199,star_job,set_initial_irradiation,.false.,,
200,star_job,set_to_this_irrad_flux,0,,
201,star_job,change_RTI_flag,.false.,,RTI variables ``RTI_flag`` is true if we are doing Rayleigh Taylor Instabilities
202,star_job,change_initial_RTI_flag,.false.,,
203,star_job,new_RTI_flag,.false.,,
204,star_job,change_RSP_flag,.false.,,RSP variables ``RSP_flag`` is true if we are doing radial stellar pulsations
205,star_job,change_initial_RSP_flag,.false.,,
206,star_job,new_RSP_flag,.false.,,
207,star_job,change_v_flag,.false.,,"velocity variables __________________ change whether MESA evolves a (radial) velocity variable, v..."
208,star_job,change_initial_v_flag,.false.,,
209,star_job,new_v_flag,.false.,,
210,star_job,center_ye_limit_for_v_flag,0.45d0,,automatically turn on velocities if ``center_ye`` drops below this limit. this is useful for evol...
211,star_job,change_u_flag,.false.,,"change whether MESA evolves a (radial) velocity variable, u, defined at cell centers. this is an ..."
212,star_job,change_initial_u_flag,.false.,,
213,star_job,new_u_flag,.false.,,
214,star_job,change_reconstruction_flag,.false.,,change whether MESA reconstruction variables with Riemann. only applies when u_flag is true.
215,star_job,change_initial_reconstruction_flag,.false.,,
216,star_job,new_reconstruction_flag,.false.,,
217,star_job,new_rotation_flag,.false.,,rotation controls _________________ rotation is enabled only if ``rotation_flag`` is true ``new_r...
218,star_job,change_rotation_flag,.false.,,
219,star_job,change_initial_rotation_flag,.false.,,
220,star_job,new_omega,0,,"the following only apply when rotation is already on (i.e., when ``rotation_flag`` is true), incl..."
221,star_job,set_omega,.false.,,
222,star_job,set_initial_omega,.false.,,
223,star_job,new_omega_div_omega_crit,0,,"as above, but sets ``omega/omega_crit`` ``omega_crit`` is defined as: gamma_factor = 1d0 - min(L_..."
224,star_job,set_omega_div_omega_crit,.false.,,
225,star_job,set_initial_omega_div_omega_crit,.false.,,
226,star_job,new_surface_rotation_v,0,,"as above, but sets surface velocity in km/sec"
227,star_job,set_surface_rotation_v,.false.,,
228,star_job,set_initial_surface_rotation_v,.false.,,
229,star_job,set_omega_step_limit,-1,,"the previous controls are ""one shot"" -- they set omega once and are done. however you might need ..."
230,star_job,set_omega_div_omega_crit_step_limit,-1,,"if ``model_number`` is <= this, then do ``set_omega_div_omega_crit``"
231,star_job,set_surf_rotation_v_step_limit,-1,,"if ``model_number`` is <= this, then do ``set_surface_rotation_v``"
232,star_job,set_near_zams_omega_steps,-1,,You might want to start a run at pre-ms but only turn on rotation when near zams rather than forc...
233,star_job,set_near_zams_omega_div_omega_crit_steps,-1,,only applies if > 0 set_omega_div_omega_crit_step_limit = model_number + set_near_zams_omega_div_...
234,star_job,set_near_zams_surface_rotation_v_steps,-1,,only applies if > 0 set_surf_rotation_v_step_limit = model_number + set_surf_rotation_v_step_limi...
235,star_job,num_steps_to_relax_rotation,100,,use ``num_steps_to_relax_rotation`` steps to relax omega to new value
236,star_job,relax_omega_max_yrs_dt,1d9,,``relax_omega_max_yrs_dt`` sets a maximum time step used during the relaxation process < 0 implie...
237,star_job,relax_omega,.false.,,"if ``relax_omega`` true, relax to value of ``new_omega``. applies when do ./rn or ./re ``relax_in..."
238,star_job,relax_initial_omega,.false.,,
239,star_job,near_zams_relax_omega,.false.,,
240,star_job,relax_omega_div_omega_crit,.false.,,"as above for ``relax_omega``, but for ``omega``/``omega_crit``"
241,star_job,relax_initial_omega_div_omega_crit,.false.,,
242,star_job,near_zams_relax_omega_div_omega_crit,.false.,,
243,star_job,relax_surface_rotation_v,.false.,,"as above for ``relax_omega``, but for surface speed"
244,star_job,relax_initial_surface_rotation_v,.false.,,
245,star_job,near_zams_relax_initial_surface_rotation_v,.false.,,
246,star_job,new_D_omega_flag,.false.,,
247,star_job,change_D_omega_flag,.false.,,
248,star_job,change_initial_D_omega_flag,.false.,,
249,star_job,new_am_nu_rot_flag,.false.,,"if ``am_nu_rot_flag`` is true, use time and space smoothed ``am_nu_rot`` like ``D_omega`` else if..."
250,star_job,change_am_nu_rot_flag,.false.,,
251,star_job,change_initial_am_nu_rot_flag,.false.,,
252,star_job,use_D_omega_for_am_nu_rot,.true.,,
253,star_job,relax_core,.false.,,"controls for nonzero center M (mass), R (radius), L (luminosity) (e.g., to model neutron star env..."
254,star_job,relax_initial_core,.false.,,
255,star_job,new_core_mass,0,,
256,star_job,dlg_core_mass_per_step,1d-3,,
257,star_job,relax_core_years_for_dt,1,,
258,star_job,core_avg_rho,10,,
259,star_job,core_avg_eps,1d-6,,
260,star_job,relax_M_center,.false.,,"Like ``relax_mass_scale``, but all change in mass goes into ``M_center``. NOTE: ``new_mass`` is n..."
261,star_job,relax_initial_M_center,.false.,,
262,star_job,relax_M_center_dt,3.1558149984d1,,
263,star_job,relax_R_center,.false.,,"as above for the mass, but for the radius. ``new_R_center`` in cm. ``relax_R_center_dt`` in seconds."
264,star_job,relax_initial_R_center,.false.,,
265,star_job,new_R_center,0,,
266,star_job,dlgR_per_step,3d-3,,
267,star_job,relax_R_center_dt,3.1558149984d1,,
268,star_job,zero_alpha_RTI,.false.,,
269,star_job,zero_initial_alpha_RTI,.false.,,
270,star_job,set_v_center,.false.,,
271,star_job,set_initial_v_center,.false.,,